spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
logging.level:
  org.hibernate.SQL: debug